# Generated by Django 4.0.1 on 2022-01-14 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_alter_carmakemodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmakemodel',
            name='id',
        ),
        migrations.AddField(
            model_name='carmakemodel',
            name='car_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmakemodel',
            name='rating',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
