# Generated by Django 4.0.1 on 2022-01-14 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_alter_carmakemodel_car_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('rating', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_rating', models.FloatField(default=0)),
                ('rates_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CarMakeModel',
        ),
    ]
