# Generated by Django 4.0.1 on 2022-01-14 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0005_car_delete_carmakemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='rates_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.PositiveBigIntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
