# Generated by Django 4.0.1 on 2022-01-15 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0007_alter_car_avg_rating_alter_car_rates_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rates_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.CreateModel(
            name='CarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_rating', models.FloatField(default=0)),
                ('rates_number', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
            ],
        ),
    ]
