# Generated by Django 4.0.1 on 2022-01-15 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0011_alter_car_avg_rating_alter_car_rates_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
