# Generated by Django 4.0.1 on 2022-02-10 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0012_alter_car_avg_rating_alter_car_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rates_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='car_app.car')),
            ],
        ),
    ]
